server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql:///big_event
    username: root
    password: 195369

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.example.lianxishougan.mapper: debug
